spring:
  profiles:
    active: dev     # 选用一个环境
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    #国际化配置
  messages:
    basename: i18n/messages #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    cache-seconds: -1  #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    encoding: UTF-8
    defaultEncoding: UTF-8  #当根据语言类型查询不到资源时,读取默认资源文件,默认资源文件格式设置
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true       # 出现错误时, 直接抛出异常
  resources:
    add-mappings: false                             # 不要为资源文件建立映射
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8          # 东八区
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  #mybatis:
  # type-aliases-package: org.anson.demo.mapper
  #mapper-locations: classpath:mapper/**/*.xml   # 当 mapper 和 xml 不在同一个包下, 需要制定 xml的路径

logging:
  config: classpath:spring-logback.xml

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8082  # 本地端口

jwt:
  issuer: zmqy    # token 的发行者
  subject: erp    # token 的题目
  audience: zmqyCustomer  # token 的客户

mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker_str    # 全局默认主键类型 雪花算法-字符串
      table-underline: false
  configuration:
    map-underscore-to-camel-case: false     # 是否开启自动驼峰命名规则（camel case）映射
    call-setters-on-nulls: true

comstom:
  page:
    defaultPageSize: 50     # 默认分页大小
  encrypt:
    key: QBnro6SPlhL5gKLPHglf # 加密的key
    salt: pryF8Lz5fi          # 加密盐值
  export:
    maxTotal: 500000          # 最大导出数量
